"""
export_positioning_memos.py
HEDGE FUND POD - Output Layer
-----------------------------

Generates standardized actionable documentation from the Simulation Engine.
Outputs Agent-Specific memos and a generalized 'latest_run_summary.json'
readable by the Dashboard UI.
"""
import json
import os

def generate_agent_memos(output_path="../outputs/positioning_memos/"):
    os.makedirs(output_path, exist_ok=True)
    print(f"Generating 5 isolated positional memos to {output_path}...")
    
    memos = {
        "quant_memo": {"position": "Short Basket (Broad Tech)", "driver": "VaR limit breach forced neutral gross deleveraging."},
        "macro_memo": {"position": "Short Sovereign Yields", "driver": "Amplifying duration shock unhedged."},
        "pod_memo":   {"position": "Neutralize Factor Beta", "driver": "PMs forced to sector-neutralize rate exposure immediately."},
        "fundie_memo":{"position": "Long MSFT", "driver": "Absorbing liquidity vacuum; prioritizing 3-year free-cash-flow over 5-day variance."},
        "activist_memo":{"position": "Hedge via VIX options", "driver": "Trapped structural capital unable to liquidate. Paying cost of carry."}
    }
    
    for filename, content in memos.items():
        with open(f"{output_path}{filename}.json", 'w') as f:
            json.dump(content, f, indent=4)

def generate_summary(output_path="../outputs/latest_run_summary.json"):
    print("Writing structural dashboard JSON payload...")
    summary = {
        "scenario_id": "SIM-2026-BETA",
        "macro_catalyst": "Bond Vigilante Duration Shock (Rates +35bps, VIX 26.5)",
        "per_agent_stance": {
            "Quant": "Deleverage and Short",
            "Macro": "Aggressive Short Bonds",
            "Pod": "Factor Hedging",
            "Fundie": "Accumulate Quality Long",
            "Activist": "Pay Volatility Premium"
        },
        "crowded_trades": ["Short Duration Tech", "Long VIX Calls"],
        "highest_conviction_trade": {
            "asset": "MSFT Equity Buy",
            "sponsoring_agent": "Fundamental Tiger",
            "confidence_driver": "Extreme liquidity vacuum generated by arbitrary Quant auto-selling."
        },
        "invalidation_conditions": "Dovish Central Bank Pivot"
    }
    with open(output_path, 'w') as f:
        json.dump(summary, f, indent=4)

if __name__ == "__main__":
    generate_agent_memos()
    generate_summary()
